apiVersion: v1
kind: ConfigMap
metadata:
  name: ecom-config
data:
  PORT: "5000"
  MONGO_URI: "mongodb://mongo-service:27017/ecommerce-app"
  JWT_EXPIRES_IN: "1h"
  CLOUD_NAME: "dtxui3q64"
  ADMIN_EMAIL: "alegnta88@gmail.com"
  ADMIN_NAME: "alegnta"
  ADMIN_PASSWORD: "alegnta"
  ADMIN_PHONE: "0938546370"
  SMS_API_URL: "http://196.190.251.17/send"
  SMS_SENDER_NAME: "6575"
  BASE_URL: "http://localhost:5000"
  REDIS_URL: "redis://redis-service:6379"