apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-app
  template:
    metadata:
      labels:
        app: ecom-app
    spec:
      containers:
        - name: ecom-app
          image: ecom-app:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: ecom-config
            - secretRef:
                name: ecom-secret